trunk/src/Register.Web/Controllers/AnounceController.cs
using CaptchaMvc.HtmlHelpers;
using CSP.Lib.Models;
using CSP.Lib.Mvc;
using Register.Models;
using Register.Web.Helpers;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Register.Web.Controllers
{
    public class AnnounceController : BaseController
    {
        // GET: Pencil/Announce
        public ActionResult Index()
        {
            return View();
        }

        [CalendarOpenFilter(CalendarCode = "SEARCH_EXAM_PASS", SystemType = "MASTER")]
        public ActionResult PassScore(int? testTypeID)
        {
            return View();
        }

        [HttpPost]
        [CSPValidateHttpAntiForgeryToken]
        public async Task<ActionResult> PassScore(InquiryModel model)
        {
            var rtn = new ResultInfo();
            ExamPassInfoModel result = null;
            var api = SysParameterHelper.ApiUrlServerSide;
            if (!this.IsCaptchaValid("Validate your captcha"))
            {
                ModelState.AddModelError("Captcha", "กรอกตัวอักษรที่อยู่บนหน้าเว็บไม่ถูกต้อง");
                rtn.Success = false;
                rtn.ErrorMessage = "กรอกตัวอักษรที่อยู่บนหน้าเว็บไม่ถูกต้อง";
            }
            else
            {
                rtn.Success = true;
                try
                {
                    using (var client = new HttpClient())
                    {
                        client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                        var response = await client.GetAsync(api + "Inquiry/ExamPassInfo?testTypeID=" + model.TestTypeID + "&citizenID=" + model.CitizenID);
                        result = await response.Content.ReadAsAsync<ExamPassInfoModel>();
                    }
                }
                catch (Exception ex)
                {
                    rtn.Success = false;
                    rtn.ErrorMessage = ex.Message;
                }
            }
            var captchaValue = this.GenerateCaptchaValue(5);
            return Json(new
            {
                rtn,
                Captcha =
                            new Dictionary<string, string>
                                {
                        {captchaValue.ImageElementId, captchaValue.ImageUrl},
                        {captchaValue.TokenElementId, captchaValue.TokenValue}
                                },
                Data = result
            });
        }

        [CalendarOpenFilter(CalendarCode = "SEARCH_SCORE", SystemType = "MASTER")]
        public ActionResult Score(int? testTypeID)
        {
            return View();
        }

        [HttpPost]
        [CSPValidateHttpAntiForgeryToken]
        public async Task<ActionResult> Score(InquiryModel model)
        {
            var rtn = new ResultInfo();
            ExamPassInfoModel result = null;
            var api = SysParameterHelper.ApiUrlServerSide;
            if (!this.IsCaptchaValid("Validate your captcha"))
            {
                ModelState.AddModelError("Captcha", "กรอกตัวอักษรที่อยู่บนหน้าเว็บไม่ถูกต้อง");
                rtn.Success = false;
                rtn.ErrorMessage = "กรอกตัวอักษรที่อยู่บนหน้าเว็บไม่ถูกต้อง";
            }
            else
            {
                rtn.Success = true;
                try
                {
                    using (var client = new HttpClient())
                    {
                        client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                        var response = await client.GetAsync(api + "Inquiry/ExamPassInfo?testTypeID=" + model.TestTypeID + "&citizenID=" + model.CitizenID + "&mobile=" + model.Mobile);
                        result = await response.Content.ReadAsAsync<ExamPassInfoModel>();
                    }
                }
                catch (Exception ex)
                {
                    rtn.Success = false;
                    rtn.ErrorMessage = ex.Message;
                }
            }
            var captchaValue = this.GenerateCaptchaValue(5);
            return Json(new
            {
                rtn,
                Captcha =
                            new Dictionary<string, string>
                                {
                        {captchaValue.ImageElementId, captchaValue.ImageUrl},
                        {captchaValue.TokenElementId, captchaValue.TokenValue}
                                },
                Data = result
            });
        }
    }
}

trunk/src/Register.Web/Controllers/LandingController.cs
using Register.Web.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;

namespace Register.Web.Controllers
{
    using CSP.Lib.Diagnostic;
    using Models;
    using System.Threading.Tasks;

    public class LandingController : BaseController
    {
        // GET: Landing
        public async Task<ActionResult> Index()
        {
            var model = new LandingPageViewModel();
            var api = SysParameterHelper.ApiUrlServerSide;
            try
            {
                using (var client = new HttpClient())
                {
                    ///client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    var response = await client.GetAsync(api + "Master/ExamTypeHomes");
                    response.EnsureSuccessStatusCode();
                    model.TesttypeList = await response.Content.ReadAsAsync<List<TesttypeListingModel>>();
                }
            }
            catch (Exception ex)
           {
                Log.WriteErrorLog(tsw.TraceError, ex);
            }                    
            return View(model);
        }
    }
}

trunk/src/Register.Web/Controllers/PhotoController.cs
using CaptchaMvc.HtmlHelpers;
using CSP.Lib.Diagnostic;
using CSP.Lib.Models;
using CSP.Lib.Mvc;
using Newtonsoft.Json;
using Register.Models;
using Register.Web.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Register.Web.Controllers
{
    public class PhotoController : BaseController
    {
        // GET: Pencil/Photo
        public ActionResult Index()
        {
            return View();
        }

        [CalendarOpenFilter(CalendarCode = "UPLOAD_PHOTO", SystemType = "MASTER")]
        public ActionResult Upload(int? testTypeID)
        {
            return View();
        }

        [HttpPost]
        [CSPValidateHttpAntiForgeryToken]
        public async Task<ActionResult> Upload(InquiryModel model)
        {
            var rtn = new ResultInfo();
            UploadStatusModel result = null;
            var api = SysParameterHelper.ApiUrlServerSide;
            if (!this.IsCaptchaValid("Validate your captcha"))
            {
                ModelState.AddModelError("Captcha", "กรอกตัวอักษรที่อยู่บนหน้าเว็บไม่ถูกต้อง");
                rtn.Success = false;
                rtn.ErrorMessage = "กรอกตัวอักษรที่อยู่บนหน้าเว็บไม่ถูกต้อง";
            }
            else
            {
                rtn.Success = true;
                try
                {
                    using (var client = new HttpClient())
                    {
                        client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                        var response = await client.GetAsync(api + "Inquiry/UploadStatus?testTypeID=" + model.TestTypeID + "&citizenID=" + model.CitizenID);
                        result = await response.Content.ReadAsAsync<UploadStatusModel>();
                    }
                }
                catch (Exception ex)
                {
                    rtn.Success = false;
                    rtn.ErrorMessage = ex.Message;
                    Log.WriteErrorLog(tsw.TraceError, ex);
                }
            }
            var captchaValue = this.GenerateCaptchaValue(5);
            return Json(new
            {
                rtn,
                Captcha =
                            new Dictionary<string, string>
                                {
                        {captchaValue.ImageElementId, captchaValue.ImageUrl},
                        {captchaValue.TokenElementId, captchaValue.TokenValue}
                                },
                Data = result
            });
        }

    }
}

trunk/src/Register.Web/Controllers/SMSController.cs
using CaptchaMvc.HtmlHelpers;
using CSP.Lib.Diagnostic;
using CSP.Lib.Models;
using CSP.Lib.Mvc;
using Newtonsoft.Json;
using Register.Models;
using Register.Web.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Register.Web.Controllers
{
    public class SMSController : BaseController
    {
        // GET: Pencil/SMS
        public ActionResult Index()
        {
            return View();
        }

        [CalendarOpenFilter(CalendarCode = "ENROLL", SystemType = "MASTER")]
        public ActionResult Register(int? testTypeID)
        {
            return View("SMSRegister");
        }

        [HttpPost]
        [CSPValidateHttpAntiForgeryToken]
        public async Task<ActionResult> Register(InquiryModel model)
        {
            var rtn = new ResultInfo();
            SMSStatusModel result = null;
            var api = SysParameterHelper.ApiUrlServerSide;
            if (!this.IsCaptchaValid("Validate your captcha"))
            {
                ModelState.AddModelError("Captcha", "กรอกตัวอักษรที่อยู่บนหน้าเว็บไม่ถูกต้อง");
                rtn.Success = false;
                rtn.ErrorMessage = "กรอกตัวอักษรที่อยู่บนหน้าเว็บไม่ถูกต้อง";
            }
            else
            {
                rtn.Success = true;
                try
                {
                    using (var client = new HttpClient())
                    {
                        client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                        var response = await client.GetAsync(api + "SMS/SMSStatus?testTypeID=" + model.TestTypeID + "&citizenID=" + model.CitizenID);
                        var jsonResult = await response.Content.ReadAsStringAsync();
                        result = JsonConvert.DeserializeObject<SMSStatusModel>(jsonResult);
                    }
                }
                catch (Exception ex)
                {
                    rtn.Success = false;
                    rtn.ErrorMessage = ex.Message;
                    Log.WriteErrorLog(tsw.TraceError, ex);
                }
            }
            var captchaValue = this.GenerateCaptchaValue(5);
            return Json(new
            {
                rtn,
                Captcha =
                            new Dictionary<string, string>
                                {
                        {captchaValue.ImageElementId, captchaValue.ImageUrl},
                        {captchaValue.TokenElementId, captchaValue.TokenValue}
                                },
                Data = result
            });
        }
    }
}

trunk/src/Register.Web/Controllers/UploadController.cs
using CSP.Lib.Models;
using CSP.Lib.Mvc;
using Newtonsoft.Json;
using Register.Models;
using Register.Web.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using CSP.Lib.Diagnostic;
using CSP.Lib.Extension;
using System.IO;

namespace Register.Web.Controllers
{
    using CSP.Lib.NetworkFile;
    using Models;

    public class UploadController : BaseController
    {
        [HttpPost]
        public ActionResult UploadDocs()
        {
            var model = new DocToUploadModel()
            {
                UPLOAD_STATUS = "N"
            };
            try
            {
                if (Request.Files.Count > 0 && Request.Files[0].ContentLength > 0)
                {
                    model.TEST_TYPE_ID = Request.Form["testtypeid"].ToInt();
                    model.DOC_TYPE_ID = Request.Form["doctypeid"].ToInt();
                    model.DOC_GUID = Guid.NewGuid();
                    var fi = Request.Files[0];
                    model.FILE_NAME = Path.GetFileName(fi.FileName);
                    model.FILE_TYPE = fi.ContentType;

                    var dest = Path.Combine(SysParameterHelper.DocUploadTempPath, model.TEST_TYPE_ID.ToString(), model.DOC_GUID.ToString().Right(3), model.DOC_GUID.ToString());
                    var domain = SysParameterHelper.PhotoDomain;
                    var user = SysParameterHelper.PhotoUser;
                    var password = SysParameterHelper.PhotoPassword;
                    NetworkFileHelper.SaveFileOverNetwork(domain, user, password, fi.InputStream, dest);

                    // check file ลง temp สำเร็จหรือไม่
                    if (NetworkFileHelper.IsFileExists(domain, user, password, dest))
                    {
                        model.UPLOAD_STATUS = "Y";
                    }
                }
            }
            catch (Exception ex)
            {
                Log.WriteErrorLog(tsw.TraceError, ex);
            }
            return Json(model);
        }

        //[HttpPost]
        //public ActionResult DownloadFromTemp(DocToUploadModel model)
        public ActionResult DownloadFromTemp(int testTypeID, string docGuid, string filename, string fileType)
        {
            try
            {
                //var dest = Path.Combine(SysParameterHelper.DocUploadTempPath, model.TEST_TYPE_ID.ToString(), model.DOC_GUID.ToString());
                var dest = Path.Combine(SysParameterHelper.DocUploadTempPath, testTypeID.ToString(), docGuid.ToString().Right(3), docGuid);
                var domain = SysParameterHelper.PhotoDomain;
                var user = SysParameterHelper.PhotoUser;
                var password = SysParameterHelper.PhotoPassword;

                return File(NetworkFileHelper.ReadFile(domain, user, password, dest), fileType, filename);
                //return File(NetworkFileHelper.ReadFile(domain, user, password, dest), model.FILE_TYPE, model.FILE_NAME);
            }
            catch (Exception ex)
            {
                Log.WriteErrorLog(tsw.TraceError, ex);
            }
            return new EmptyResult();
        }


    }
}

trunk/src/Register.Web/Views/Shared/_Footer.cshtml
<footer class="footer d-none d-md-block py-2">
    หากมีปัญหาเกี่ยวกับระบบรับสมัคร ติดต่อ Call Center โทร. 0-2697-0999 กด 902 ในวันจันทร์-ศุกร์ เวลา 8.30-17.30 น.
   @* <br />หากมีข้อสงสัยเกี่ยวกับคุณสมบัติในการสมัครสอบ ติดต่อ กรมการพัฒนาชุมชน โทร. 02-141-6379, 02-141-6173, 02-141-6200, 02-141-6174, และ 02-141-2675 ในวันและเวลาราชการ*@
    <br />Version : @Html.GetAppVersion() [@CSP.Lib.Mvc.SystemHelper.GetServerIPLast3()]
</footer>
<footer class="footer d-md-none py-2">
    หากมีปัญหาเกี่ยวกับระบบรับสมัคร ติดต่อ Call Center โทร. 0-2697-0999 กด 902
    <br />ในวันจันทร์-ศุกร์ เวลา 8.30-17.30 น.
    @*<br />หากมีข้อสงสัยเกี่ยวกับคุณสมบัติในการสมัครสอบ ติดต่อ กรมการพัฒนาชุมชน 
    <br />โทร. 02-141-6379, 02-141-6173, 02-141-6200, 02-141-6174, และ 02-141-2675 ในวันและเวลาราชการ*@
    <br />Version : @Html.GetAppVersion() [@CSP.Lib.Mvc.SystemHelper.GetServerIPLast3()]
</footer>

trunk/src/Register.Web/Views/Shared/_Footer3.cshtml
<footer class="footer d-none d-md-block py-2">
    หากมีปัญหาเกี่ยวกับระบบรับสมัคร ติดต่อ Call Center โทร. 0-2697-0999 กด 1 แล้วกด 902 ในวันจันทร์-ศุกร์ เวลา 8.30-17.30 น.
    <br />หากมีข้อสงสัยเกี่ยวกับคุณสมบัติในการสมัครสอบ ติดต่อ กลุ่มงานจัดการงานบุคคล 1 โทร. 0-2026-5555 ต่อ 1408 ในวันและเวลาราชการ
    <br />Version : @Html.GetAppVersion() [@CSP.Lib.Mvc.SystemHelper.GetServerIPLast3()]
</footer>
<footer class="footer d-md-none py-2">
    หากมีปัญหาเกี่ยวกับระบบรับสมัคร ติดต่อ Call Center โทร. 0-2697-0999 กด 1 แล้วกด 902
    <br />ในวันจันทร์-ศุกร์ เวลา 8.30-17.30 น.
    <br />หากมีข้อสงสัยเกี่ยวกับคุณสมบัติในการสมัครสอบ ติดต่อ กลุ่มงานจัดการงานบุคคล 1 
    <br />โทร. 0-2026-5555 ต่อ 1408 ในวันและเวลาราชการ
    <br />Version : @Html.GetAppVersion() [@CSP.Lib.Mvc.SystemHelper.GetServerIPLast3()]
</footer>

trunk/src/Register.Web/Views/Shared/_LoadingNextTo.cshtml
@{
    var ngModel = ViewData.Eval("ng_model");
}
<div class="text-info my-auto" role="status" ng-show="getLoading('@ngModel')">
    <span><img src="~/Content/Images/5.gif" style="width: 25px;height:25px;" /></span>
</div>

trunk/src/Register.Web/Views/Shared/_SideBar_TestType2.cshtml
@{
    var testTypeID = this.ViewContext.RouteData.GetRequiredString("testtypeid");
}
<script src="~/Scripts/views/_sidebar.js?_=202103030404"></script>
<nav id="sidebar" ng-app="registerApp" ng-controller="sideBarController">
    <div class="sidebar-header text-center">
        <a href="@Url.Action("Index","Landing")">
            @{
                var logoFile = String.Format("~/Content/Images/logo-testType{0}.png", testTypeID);
                var absolutePath = HttpContext.Current.Server.MapPath(logoFile);
                if (System.IO.File.Exists(absolutePath))
                {
                    <img class="sidebar-logo" src="@Url.Content(logoFile)?_=20220511" />
                }
                else
                {
                    <img class="sidebar-logo" src="~/Content/Images/logo.png?_=20220511" />
                }
            }
        </a>
    </div>
    <ul class="sidebar-menu" data-widget="tree">
        <li>
            <a class="menu-item" href='@Url.Action("Index","Home")'>
                <div class="menu-item-icon"><i class="align-self-center fas fa-home"></i></div>
                <div class="menu-item-text">หน้าหลัก</div>
            </a>
        </li>
        @*<li ng-class="{'disCalendar': !IsScheduleOpen('QA')}">
            <a class="menu-item" href="~/Docs/@testTypeID/vec2020042_3.pdf" target="_blank">
                <div class="menu-item-icon"><i class="fas fa-book"></i></div>
                <div class="menu-item-text">คำถามที่พบบ่อย</div>
            </a>
        </li>*@
        <li ng-class="{'disCalendar': !IsScheduleOpen('QA')}">      
            <a class="menu-item" href="@Url.Action("Faq","Home")">
            @*<a class="menu-item"href="~/Docs/1/VEC_คำถามที่พบบ่อย.pdf" download>*@
                <div class="menu-item-icon"><i class="fas fa-book"></i></div>
                <div class="menu-item-text">สารพันปัญหา</div>
            </a>
        </li>
        @*<li ng-class="{'disCalendar': !IsScheduleOpen('ENROLL_MANUAL')}">
            <a class="menu-item" href="~/Content/Files/howto_exam.pdf?_=202103031901" target="_blank">
            <div class="menu-item-icon"><i class="fas fa-book"></i></div>
            <div class="menu-item-text">คู่มือแนะนำการสมัครสอบ</div></a>
        </li>*@
        <li ng-class="{'disCalendar': !IsScheduleOpen('ENROLL')}">
            <a class="menu-item" href="@Url.Action("Register", "Register")" data-toggle="tooltip" data-placement="right"
               title="{{ (IsScheduleOpen('ENROLL')) ? '' : ''}}" 
               data-original-title="{{ (IsScheduleOpen('ENROLL')) ? '' : ''}}">
                <div class="menu-item-icon"><i class="fas fa-pencil-alt"></i></div>
                <div class="menu-item-text">สมัครสอบ</div>
            </a>
        </li>
        @*<li>
            <a class="menu-item" href="http://e-accreditation.ocsc.go.th/acc/index.html" target="_blank">
                <div class="menu-item-icon"><i class="fas fa-graduation-cap"></i></div>
                <div class="menu-item-text">ตรวจสอบคุณวุฒิ<br />ตามที่ ก.พ. รับรอง</div>
            </a>
        </li>
        <li>
            <a class="menu-item" href="https://gencer.ocsc.go.th/login.aspx" target="_blank">
                <div class="menu-item-icon"><i class="fas fa-book-open"></i></div>
                <div class="menu-item-text">ค้นหาหนังสือรับรองผล<br />การสอบผ่านการวัดความรู้<br />ความสามารถทั่วไป ก.พ.</div>
            </a>
        </li>*@
        <li ng-class="{'disCalendar': !IsScheduleOpen('PRINT_PAYIN')}">
            <a class="menu-item" href="@Url.Action("PaymentStatus","Inquiry")" data-toggle="tooltip" data-placement="right"
               title="{{ (IsScheduleOpen('PRINT_PAYIN')) ? '' : ''}}" 
               data-original-title="{{ (IsScheduleOpen('PRINT_PAYIN')) ? '' : ''}}">
                <div class="menu-item-icon"><span class="font-weight-bold information">฿</span></div>
                <div class="menu-item-text">ค้นหาแบบฟอร์มการชำระเงิน</div>
            </a>
        </li>
        <li ng-class="{'disCalendar': !IsScheduleOpen('ENROLL_CHECK_STATUS')}">
            <a class="menu-item" href="@Url.Action("RegisterStatus","Inquiry")" data-toggle="tooltip" data-placement="right"
               title="{{ (IsScheduleOpen('ENROLL_CHECK_STATUS')) ? '' : ''}}" 
               data-original-title="{{ (IsScheduleOpen('ENROLL_CHECK_STATUS')) ? '' : ''}}">
                <div class="menu-item-icon"><i class="fas fa-tasks"></i></div>
                <div class="menu-item-text">ตรวจสอบสถานะ<br />การสมัครสอบ</div>
            </a>
        </li>
        @*<li ng-class="{'disCalendar': !IsScheduleOpen('UPLOAD_PHOTO')}">
            <a class="menu-item" href="@Url.Action("Upload", "Photo")" data-toggle="tooltip" data-placement="right"
               title="{{ (IsScheduleOpen('UPLOAD_PHOTO')) ? '' : ''}}"
               data-original-title="{{ (IsScheduleOpen('UPLOAD_PHOTO')) ? '' : ''}}">
                <div class="menu-item-icon"><i class="fas fa-scroll"></i></div>
                <div class="menu-item-text">อัปโหลดรูปถ่ายใหม่<br />กรณีรูปถ่ายไม่ถูกต้อง</div>
            </a>
        </li>*@
        @*<li ng-class="{'disCalendar': !IsScheduleOpen('REUPLOAD_DOC')}">
            <a class="menu-item" href="@Url.Action("Index", "ReUploadDocs")" data-toggle="tooltip" data-placement="right"
               title="{{ (IsScheduleOpen('PRINT_PAYIN')) ? '' : ''}}"
               data-original-title="{{ (IsScheduleOpen('PRINT_PAYIN')) ? '' : ''}}">
                <div class="menu-item-icon"><i class="far fa-file-alt"></i></div>
                <div class="menu-item-text">อัปโหลดเอกสารใหม่</div>
            </a>
        </li>*@
        <li ng-class="{'disCalendar': !IsScheduleOpen('PRINT_EXAM_APPLICATION')}">
            <a class="menu-item" href="@Url.Action("ExamApplication","Inquiry")" data-toggle="tooltip" data-placement="right"
               title="{{ (IsScheduleOpen('PRINT_EXAM_APPLICATION')) ? '' : ''}}" 
               data-original-title="{{ (IsScheduleOpen('PRINT_EXAM_APPLICATION')) ? '' : ''}}">
                <div class="menu-item-icon"><i class="fas fa-print"></i></div>
                <div class="menu-item-text">พิมพ์ใบสมัคร</div>
            </a>
        </li>
        <li ng-class="{'disCalendar': !IsScheduleOpen('GET_EXAM_SITE_PRINT_EXAM_CARD')}">
            <a class="menu-item" href="@Url.Action("SeatInfo", "Inquiry")" data-toggle="tooltip" data-placement="right"
               title="{{ (IsScheduleOpen('GET_EXAM_SITE_PRINT_EXAM_CARD')) ? '' : ''}}"
               data-original-title="{{ (IsScheduleOpen('GET_EXAM_SITE_PRINT_EXAM_CARD')) ? '' : ''}}">
                <div class="menu-item-icon"><i class="fas fa-map-marked-alt"></i></div>
                <div class="menu-item-text">ค้นหาสถานที่สอบ<br />และพิมพ์บัตรประจำตัวสอบ</div>
            </a>
        </li>
        <li ng-class="{'disCalendar': !IsScheduleOpen('ENROLL')}">
            <a class="menu-item" href="@Url.Action("Register", "SMS")" data-toggle="tooltip" data-placement="right"
               title="{{ (IsScheduleOpen('ENROLL')) ? '' : ''}}"
               data-original-title="{{ (IsScheduleOpen('ENROLL')) ? '' : ''}}">
                <div class="menu-item-icon"><i class="fas fa-sms"></i></div>
                <div class="menu-item-text">สมัคร SMS แจ้งเตือน</div>
            </a>
        </li>
        @*<li ng-class="{'disCalendar': !IsScheduleOpen('REFUND_REPEATED_PAYMENTS')}">
            <a class="menu-item" href="@Url.Action("PaymentRepeated","Inquiry")" data-toggle="tooltip" data-placement="right"
               title="{{ (IsScheduleOpen('REFUND_REPEATED_PAYMENTS')) ? '' : 'ระบบเริ่มเปิดวันที่ 22 มี.ค. 64'}}"
               data-original-title="{{ (IsScheduleOpen('REFUND_REPEATED_PAYMENTS')) ? '' : 'ระบบเริ่มเปิดวันที่ 22 มี.ค. 64'}}">
                <div class="menu-item-icon"><i class="fas fa-hand-holding-usd"></i></div>
                <div class="menu-item-text">ขอคืนเงิน กรณีชำระซ้ำ</div>
            </a>
        </li>*@
        @*<li ng-class="{'disCalendar': !IsScheduleOpen('SEARCH_EXAM_PASS')}">
            <a class="menu-item" href="@Url.Action("PassScore","Announce")" data-toggle="tooltip" data-placement="right"
               title="{{ (IsScheduleOpen('SEARCH_EXAM_PASS')) ? '' : 'ระบบยังไม่เปิดให้บริการ !'}}" 
               data-original-title="{{ (IsScheduleOpen('SEARCH_EXAM_PASS')) ? '' : 'ระบบยังไม่เปิดให้บริการ !'}}">
                <div class="menu-item-icon"><i class="fas fa-search"></i></div>
                <div class="menu-item-text">ค้นหารายชื่อ<br />ผู้สอบผ่านข้อเขียน</div>
            </a>
        </li>*@
        @*<li class="" ng-class="{'disCalendar': !IsScheduleOpen('SEARCH_SCORE')}">
            <a class="menu-item" href="@Url.Action("Score","Announce")" data-toggle="tooltip" data-placement="right" 
               title="{{ (IsScheduleOpen('SEARCH_SCORE')) ? '' : 'ระบบยังไม่เปิดให้บริการ !'}}" 
               data-original-title="{{ (IsScheduleOpen('SEARCH_SCORE')) ? '' : 'ระบบยังไม่เปิดให้บริการ !'}}">
                <div class="menu-item-icon"><i class="fas fa-scroll"></i></div>
                <div class="menu-item-text">ดูผลคะแนนสอบ</div>
            </a>
        </li>*@
        @*<li>
            <a class="menu-item" href="http://qualification60.otepc.go.th/login.php" target="_blank">
                <div class="menu-item-icon"><i class="fas fa-stamp"></i></div>
                <div class="menu-item-text">ตรวจสอบคุณวุฒิที่รับรองเป็นข้าราชการครู</div>
            </a>
        </li>*@
    </ul>
</nav>
<script>
$(document).ready(function(){
  $('[data-toggle="tooltip"]').tooltip();
});
</script>