trunk/src/Register.Web/Models/RegisterViewModels.cs
using Register.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Register.Web.Models
{
    public class RegisterViewModels : RegisterModel
    {
        //public List<PrefixModel> PrefixSelect { get; set; }
    }
}

trunk/src/Register.Web/Controllers/ReportsController.cs
using CSP.Lib.Extension;
using CSP.Lib.Json;
using CSP.Lib.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

using Register.Reports;
using Register.Reports.Helpers;
using Register.Web.Helpers;
using System;
using io = System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using CSP.Lib.Mvc;
using CSP.Lib.Diagnostic;
using System.Data;

namespace Register.Web.Controllers
{
    public class ReportsController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }
   
        [HttpPost]
        [CSPValidateHttpAntiForgeryToken]
        public async Task<ActionResult> PrintPayin(int testTypeID, string citizenID)
        {
            byte[] result = null;
            var api = SysParameterHelper.ApiUrlServerSide;
            var jsonResult = string.Empty;
            var localFile = "";

            PayinReport rpt = new PayinReport();
            try
            {
                using (var client = new HttpClient())
                {
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    var response = await client.GetAsync(api + "Reports/Payin?testTypeID=" + testTypeID + "&citizenID=" + citizenID);
                    response.EnsureSuccessStatusCode();
                    jsonResult = await response.Content.ReadAsStringAsync();
                    rpt.IsTesting = SysParameterHelper.IsTesting;
                    rpt.JsonData = jsonResult;
                    rpt.RefreshDataSource();
                }
                result = rpt.GetReport();
                localFile = String.Format("Payin_{0}_{1}.pdf", citizenID, DateTime.Now.ToString("yyyyMMddHHmmss"));
            }
            catch (Exception ex)
            {
                Log.WriteErrorLog(tsw.TraceError, ex);
                throw (ex);
            }

            var datas = (JObject)JsonConvert.DeserializeObject(jsonResult);
            var smsStatus = (datas?.GetValueIgnoreCase("SMS_STATUS")).ToBoolean();
            if (smsStatus)
            {
                SMSPayinReport rptSub = new SMSPayinReport();
                try
                {
                    byte[] resultSub = null;
                    rptSub.IsTesting = SysParameterHelper.IsTesting;
                    rptSub.JsonData = jsonResult;
                    rptSub.RefreshDataSource();

                     resultSub = rptSub.GetReport();
                    if (resultSub !=null)
                    {
                        // Merge 2 ใบเข้าด้วยกัน
                        var docs = new byte[][] { result, resultSub };
                        var newTarget = (localFile as string).Replace(".pdf", "WithSMS.pdf");

                        var mergePdf = PdfHelper.MergePDFs(docs, newTarget);
                        if(mergePdf != null)
                        {
                            result = mergePdf;
                            localFile = newTarget;
                        }
                        //if (PdfHelper.MergePDFs(docs, newTarget))
                        //{
                        //    localFile = newTarget;
                        //}

                    }
                }
                catch (Exception ex)
                {
                    Log.WriteErrorLog(tsw.TraceError, ex);
                    throw (ex);
                }
            }

            if (result == null)
            {
                return Content("ไม่มีข้อมูล");
            }
            return File(result, "application/pdf", localFile);
        }

        [HttpPost]
        [CSPValidateHttpAntiForgeryToken]
        public async Task<ActionResult> PrintExamCard(int testTypeID, string citizenID)
        {
            byte[] result = null;
            var api = SysParameterHelper.ApiUrlServerSide;
            var jsonResult = string.Empty;

            ExamCardReport rpt = new ExamCardReport();
            try
            {
                using (var client = new HttpClient())
                {
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    var response = await client.GetAsync(api + "Inquiry/ExamSiteInfo?testTypeID=" + testTypeID + "&citizenID=" + citizenID);
                    jsonResult = await response.Content.ReadAsStringAsync();
                    rpt.IsTesting = SysParameterHelper.IsTesting;
                    rpt.JsonData = jsonResult;
                    rpt.RefreshDataSource();
                    rpt.ImageBase64 = GetImageBase64ForReport(testTypeID, citizenID);
                }
                result = rpt.GetReport();

            }
            catch (Exception ex)
            {
                Log.WriteErrorLog(tsw.TraceError, ex);
                throw (ex);
            }

            if (result == null)
            {
                return Content("ไม่มีข้อมูล");
            }
            return File(result, "application/pdf", String.Format("Application_{0}_{1}.pdf", citizenID, DateTime.Now.ToString("yyyyMMddHHmmss")));
        }



        [HttpPost]
        [CSPValidateHttpAntiForgeryToken]
        public async Task<ActionResult> PrintApplication(int testTypeID, string citizenID, string laserCode)
        {
            byte[] result = null;
            var api = SysParameterHelper.ApiUrlServerSide;
            var jsonResult = string.Empty;

            ApplicationReport rpt = new ApplicationReport(testTypeID);
            try
            {
                using (var client = new HttpClient())
                {
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    var response = await client.GetAsync(api + "Inquiry/ExamCrystalApplication?testTypeID=" + testTypeID + "&citizenID=" + citizenID + "&laserCode=" + laserCode);
                    jsonResult = await response.Content.ReadAsStringAsync();
                    DataSet ds = JsonConvert.DeserializeObject<DataSet>(jsonResult);
                    ds.Tables[0].TableName = "MainInfo";
                    ds.Tables[1].TableName = "SubStudy";
                    ds.Tables[2].TableName = "SubExperience";
                    rpt.ds = ds;
                    rpt.JsonData = jsonResult;
                    rpt.RefreshDataSource();
                    rpt.ImageByte = GetImageByteForReport(testTypeID, citizenID);
                }
                result = rpt.GetCrystalReport(citizenID);

                if (result == null)
                {
                    return Content("ไม่มีข้อมูล"); 
                }
            }
            catch (Exception ex)
            {
                Log.WriteErrorLog(tsw.TraceError, ex);
                return Content("ไม่มีข้อมูล");
            }
            return File(result, "application/pdf", String.Format("Application_{0}_{1}.pdf", citizenID, DateTime.Now.ToString("yyyyMMddHHmmss")));

        }

        //[HttpPost]
        //[CSPValidateHttpAntiForgeryToken]
        //public async Task<ActionResult> PrintApplication(int testTypeID, string citizenID, string mobileNo)
        //{
        //    ResultInfo result = new ResultInfo();
        //    var reportOutputFolder = "~/temp";
        //    var api = SysParameterHelper.ApiUrlServerSide;
        //    var jsonResult = string.Empty;

        //    ApplicationReport rpt = new ApplicationReport(testTypeID); 
        //    try
        //    { 
        //        using (var client = new HttpClient())
        //        {
        //            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        //            var response = await client.GetAsync(api + "Inquiry/ExamApplication?testTypeID=" + testTypeID + "&citizenID=" + citizenID + "&laserCode=" + "" + "&mobileNo=" + mobileNo);
        //            jsonResult = await response.Content.ReadAsStringAsync();
        //            rpt.IsTesting = SysParameterHelper.IsTesting;
        //            rpt.JsonData = jsonResult;
        //            rpt.RefreshDataSource();
        //            rpt.ImageBase64 = GetImageBase64ForReport(testTypeID, citizenID);
        //        }
        //        result = rpt.GetReport(reportOutputFolder);
        //    }
        //    catch (Exception ex)
        //    {
        //        result.Success = false;
        //        result.ErrorMessage = ex.Message;
        //    }

        //    if (result.Success)
        //    {
        //        var pdfName = result.ReturnValue1 as string;
        //        var clientFileName = System.IO.Path.GetFileName(pdfName);
        //        Response.ContentType = "application/pdf";
        //        Response.AddHeader("content-disposition", "attachment; filename=" + clientFileName);
        //        Response.TransmitFile(pdfName);
        //    }

        //    return Content(result?.ErrorMessage);
        //}

        [HttpPost]
        [CSPValidateHttpAntiForgeryToken]
        public async Task<ActionResult> PrintSmsPayIn(int testTypeID, string citizenID)
        {
            byte[] result = null;
            var api = SysParameterHelper.ApiUrlServerSide;
            var jsonResult = string.Empty;

            SMSPayinReport rpt = new SMSPayinReport();
            try
            {
                using (var client = new HttpClient())
                {
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    var response = await client.GetAsync(api + "Reports/Payin?testTypeID=" + testTypeID + "&citizenID=" + citizenID);
                    response.EnsureSuccessStatusCode();
                    jsonResult = await response.Content.ReadAsStringAsync();
                    rpt.IsTesting = SysParameterHelper.IsTesting;

trunk/src/Register.Web/Controllers/UploadController.cs
using CSP.Lib.Models;
using CSP.Lib.Mvc;
using Newtonsoft.Json;
using Register.Models;
using Register.Web.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using CSP.Lib.Diagnostic;
using CSP.Lib.Extension;
using System.IO;

namespace Register.Web.Controllers
{
    using CSP.Lib.NetworkFile;
    using Models;

    public class UploadController : BaseController
    {
        [HttpPost]
        public ActionResult UploadDocs()
        {
            var model = new DocToUploadModel()
            {
                UPLOAD_STATUS = "N"
            };
            try
            {
                if (Request.Files.Count > 0 && Request.Files[0].ContentLength > 0)
                {
                    model.TEST_TYPE_ID = Request.Form["testtypeid"].ToInt();
                    model.DOC_TYPE_ID = Request.Form["doctypeid"].ToInt();
                    model.DOC_GUID = Guid.NewGuid();
                    var fi = Request.Files[0];
                    model.FILE_NAME = Path.GetFileName(fi.FileName);
                    model.FILE_TYPE = fi.ContentType;

                    var dest = Path.Combine(SysParameterHelper.DocUploadTempPath, model.TEST_TYPE_ID.ToString(), model.DOC_GUID.ToString().Right(3), model.DOC_GUID.ToString());
                    var domain = SysParameterHelper.PhotoDomain;
                    var user = SysParameterHelper.PhotoUser;
                    var password = SysParameterHelper.PhotoPassword;
                    NetworkFileHelper.SaveFileOverNetwork(domain, user, password, fi.InputStream, dest);

                    // check file ลง temp สำเร็จหรือไม่
                    if (NetworkFileHelper.IsFileExists(domain, user, password, dest))
                    {
                        model.UPLOAD_STATUS = "Y";
                    }
                }
            }
            catch (Exception ex)
            {
                Log.WriteErrorLog(tsw.TraceError, ex);
            }
            return Json(model);
        }

        //[HttpPost]
        //public ActionResult DownloadFromTemp(DocToUploadModel model)
        public ActionResult DownloadFromTemp(int testTypeID, string docGuid, string filename, string fileType)
        {
            try
            {
                //var dest = Path.Combine(SysParameterHelper.DocUploadTempPath, model.TEST_TYPE_ID.ToString(), model.DOC_GUID.ToString());
                var dest = Path.Combine(SysParameterHelper.DocUploadTempPath, testTypeID.ToString(), docGuid.ToString().Right(3), docGuid);
                var domain = SysParameterHelper.PhotoDomain;
                var user = SysParameterHelper.PhotoUser;
                var password = SysParameterHelper.PhotoPassword;

                return File(NetworkFileHelper.ReadFile(domain, user, password, dest), fileType, filename);
                //return File(NetworkFileHelper.ReadFile(domain, user, password, dest), model.FILE_TYPE, model.FILE_NAME);
            }
            catch (Exception ex)
            {
                Log.WriteErrorLog(tsw.TraceError, ex);
            }
            return new EmptyResult();
        }


    }
}

trunk/src/Register.Web/Views/Register/ChooseRegion.cshtml
@{
    ViewBag.Title = "สมัครสอบแข่งขัน อปท. - เลือก ภาค/เขต ที่เปิดรับสมัคร";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row justify-content-center" ng-controller="ChooseRegionControler" ng-cloak>
    <div class="col-md-10 text-center border rounded py-4">
        <h4 class="mx-auto animated fadeIn text-info font-weight-bolder">เลือก ภาค/เขต ที่เปิดรับสมัคร</h4>
        <div ng-loading="isLoading.examCenters"></div>
        <table class="table table-hover w-100 my-md-2 my-sm-1 animated fadeIn">
            <thead>
                <tr>
                    <th class="text-left" colspan="2">ภาค/เขต ที่เปิดรับสมัคร</th>
                    @*<th class="text-center" style="width:25%">อัตราว่างที่บรรจุ</th>*@
                    @*<th class="text-center" style="width:50%"></th>*@
                </tr>
            </thead>
            <tbody>
                <tr class="vertical-align-middle animated fadeIn" ng-repeat="center in examCenters" >
                    <td class="text-left vertical-align-middle" style="width: 70%">{{center.CENTER_NAME}}</td>
                    @*<td class="text-center vertical-align-middle">{{center.QUOTA_QTY}}</td>*@
                    <td class="text-center vertical-align-middle">                        
                        <a class="btn btn-success" href='@Url.Action("ChoosePosition")?centerID={{center.CENTER_ID}}&centerName={{center.CENTER_NAME | escape}}'>
                            <i class="fas fa-mouse"></i>&nbsp;คลิกที่นี่เพื่อสมัคร
                        </a>
                    </td>
                </tr>
            </tbody>
            <tfoot></tfoot>
        </table>
        <a class="btn btn-secondary mt-4" href="@Url.Action("Index")">ย้อนกลับ</a>
    </div>
</div>

@section scripts {
    <script type="text/javascript" src="~/Scripts/views/register-choose-region.js"></script>
}

trunk/src/Register.Web/Views/Register/RegisterFinal.cshtml
@model Register.Models.RegisterModel
@{
    ViewBag.Title = "สมัครสอบ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row" ng-app="registerApp" ng-controller="registerFinalController">
    <div class="col-12 px-1 px-md-3">
        <div class="card mt-3">
            <h5 class="card-header header-table">สมัครสอบ</h5>
            <div class="card-body form-group pl-3">
                <div class="text-danger text-center information font-weight-bold">ระบบได้รับใบสมัครของท่านเรียบร้อยแล้ว</div>
                @*<div class="text-center mt-3 information font-weight-bold">ผู้สมัครสามารถพิมพ์ใบสมัครได้ โดยคลิกที่ปุ่มเมนู "พิมพ์ใบสมัคร"</div>*@
                <div class="text-blue text-center information font-weight-bold mt-3">การสมัครสอบจะเสร็จสมบูรณ์ต่อเมื่อผู้สมัครสอบชำระค่าธรรมเนียมในการสมัครสอบแล้ว</div>
                <div class="text-center information font-weight-bold mt-3">หลังจากที่ผู้สมัครชำระเงินค่าสมัครสอบแล้ว <span class="text-danger">ระบบจะปรับปรุงสถานะการชำระเงิน</span> <h4 class="d-inline font-weight-bold" style="color:red;">ภายในวันถัดไป</h4><br />ผู้สมัครสามารถเข้ามาตรวจสอบสถานะการชำระเงิน โดยคลิกที่ปุ่มเมนู "ตรวจสอบสถานะการสมัครสอบ"</div>

                @*<div class="text-center mt-3 information">ท่านสามารถชำระเงินค่าสมัครสอบได้ 2 ช่องทาง ดังต่อไปนี้</div>*@
                @*<div class="row mt-5">
                        <div class="col-12 col-md-2"></div>
                        <div class="col-12 col-md-4 text-left">- ชำระเงินออนไลน์ ผ่านบัตรเครดิต, บัตรเดบิต</div>
                        <div class="col-12 col-md-6">
                            <a href="https://www.ktbnetbank.com/consumer/" target="_blank" class="btn btn-success ml-md-5 mb-3"><i class="far fa-credit-card"></i>&nbsp;&nbsp;ชำระเงินออนไลน์</a>
                        </div>
                    </div>*@
                <div class="row mt-3 ng-cloak">
                    <div class="col-12 col-md-2"></div>
                    <div class="col-12 col-md-10 text-left">

                        <div ng-show="testTypeID == 2">
                            ค่าธรรมเนียมการสมัครสอบ<span class="text-danger" style="text-decoration: underline;">รวมค่าธรรมเนียมธนาคาร</span> สำหรับตำแหน่ง ดังต่อไปนี้<br>
                            1) ตำแหน่งนักทรัพยากรบุคคล จำนวน 430 บาท<br>
                            2) ตำแหน่งนักส่งเสริมการพัฒนาชุมชน จำนวน 430 บาท<br>
                            3) ตำแหน่งนักวิเคราะห์นโยบายและแผน จำนวน 430 บาท<br>
                            4) ตำแหน่งนักประชาสัมพันธ์ จำนวน 430 บาท<br>
                            5) ตำแหน่งวิศวกรโยธา จำนวน 430 บาท<br>
                            6) ตำแหน่งนักวิชาการพัสดุ จำนวน 430 บาท<br>
                            <span class="text-blue">
                                และจำนวน 400 บาท สำหรับตำแหน่งนายช่างไฟฟ้า
                            </span><br>
                            <span class="text-danger blink_me">*<span style="text-decoration: underline;">คำเตือน</span> กรณีชำระผ่านแอปพลิเคชัน กรุณาตรวจสอบยอดเงินให้ตรงกับตำแหน่งที่สมัคร</span>
                        </div>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-12 col-md-2"></div>
                    <div class="col-12 col-md-5 text-left align-self-center">1.  พิมพ์แบบฟอร์มการชำระเงิน นำไปชำระเงินที่เคาน์เตอร์ของธนาคารกรุงไทย</div>
                    <div class="col-12 col-md-5">
                        @using (Html.BeginForm("PrintPayIn", "Reports", FormMethod.Post, new { area = "", enctype = "multipart/form-data", @target = "_blank" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.Hidden("ReportName", "PayinReport")
                            <input type="hidden" id="TestTypeID" name="TestTypeID" value="{{testTypeID}}" />
                            <input type="hidden" id="CitizenID" name="CitizenID" value="@Model.CitizenID" />
                            <button type="submit" target="_blank" class="btn btn-info ml-md-5 mb-3"><i class="far fa-file-pdf fa-1x"></i>&nbsp;&nbsp;พิมพ์แบบฟอร์มการชำระเงิน</button>
                        }
                    </div>
                </div>
                <div class="row mt-3 ng-cloak">
                    <div class="col-12 col-md-2"></div>
                    <div class="col-12 col-md-10 text-left">2. ชำระเงินโดยการสแกน QR code ผ่านแอปพลิเคชัน Krungthai NEXT </div>
                </div>

                <div class="row mt-3 ng-cloak">
                    <div class="col-12 col-md-2"></div>
                    <div class="col-12 col-md-10 text-left text-danger">** QR CODE ชำระเงินนี้ ใช้สำหรับผู้สมัครที่แสดงชื่อบนฟอร์มชำระเงินนี้เท่านั้น ไม่สามารถใช้ชำระเงินให้กับผู้สมัครคนอื่นได้ **</div>
                </div>

                <div class="row mt-5 ng-cloak">
                    <div class="col-12 col-md-2" ng-if="qrcodeInfo.SmsStatus == 'Y'"></div>
                    <div class="col-12 col-md-4" ng-if="qrcodeInfo.SmsStatus == 'N'"></div>
                    <div class="col-12 col-md-4 text-center">
                        <label class="font-weight-bold information">ค่าธรรมเนียมการสอบ 400 บาท</label><br /><label class="font-weight-bold">และค่าธรรมเนียมธนาคาร 30 บาท</label><br />
                        <a id="imgQrRegister" href="{{qrcodeInfo.QRCode}}" target="_blank" download="QrCode.jpg">
                            <img ng-src="{{qrcodeInfo.QRCode}}" style="max-width: 250px; border: solid 1px black" />
                        </a><br />
                        <button type="button" class="btn btn-outline-info mt-2" onclick="imgQrRegister.click()">ดาวน์โหลด QR Code</button>
                    </div>
                    <div class="col-12 col-md-4 text-center" ng-if="qrcodeInfo.SmsStatus == 'Y'">
                        <label class="font-weight-bold">ค่าบริการ SMS 20 บาท</label><br /><label class="font-weight-bold text-danger">**ไม่ใช่ค่าสมัครสอบ**</label><br />
                        <a id="imgQrSMS" href="{{qrcodeInfo.SMSQRCode}}" target="_blank" download="QrCode-SMS.jpg">
                            <img ng-src="{{qrcodeInfo.SMSQRCode}}" style="max-width: 250px; border: solid 1px black" />
                        </a><br />
                        <button type="button" class="btn btn-outline-info mt-2" onclick="imgQrSMS.click()">ดาวน์โหลด QR Code</button>
                    </div>
                </div>
                @*<div class="row mt-5 ng-cloak"  ng-if="qrcodeInfo.SmsStatus == 'Y'">
                    <div class="col-12 col-md-4" ></div>
                    <div class="col-12 col-md-4 text-center">
                        <label class="font-weight-bold">ค่าบริการ SMS 20 บาท</label><br /><label class="font-weight-bold text-danger">**ไม่ใช่ค่าสมัครสอบ**</label><br />
                        <a id="imgQrSMS" href="{{qrcodeInfo.SMSQRCode}}" target="_blank" download="QrCode-SMS.jpg">
                            <img ng-src="{{qrcodeInfo.SMSQRCode}}" style="max-width: 250px; border: solid 1px black" />
                        </a><br />
                        <button type="button" class="btn btn-outline-info mt-2" onclick="imgQrSMS.click()">ดาวน์โหลด QR Code</button>
                    </div>
                </div>*@

                    @*<div class="row mt-3">
                <div class="col-12 offset-md-1 col-md-10 text-center">
                    <img src="~/Content/Images/banklist3.png" style="max-width: 100%; border: solid 1px black" />
                </div>

            </div>*@
                    <div class="row mt-5">
                        <div class="col-12 col-md-12 text-center">
                            <a href="@Url.Action("Index","Home")" class="btn btn-primary ml-1"><i class="fas fa-home"></i> กลับหนัาหลัก</a>
                        </div>
                    </div>
                </div>
        </div>
    </div>
</div>

@section scripts {
    <script src="~/Scripts/views/register-final.js"></script>
    <script>
        var citizenID = '@Model.CitizenID';
    </script>
}

trunk/src/Register.Web/Views/Register/_DocsUploadListConfirm.cshtml
@model List<DocToUploadModel>

@if (Model != null)
{
    <div id="divUploadDoc" ng-controller="uploadDocsController" class="table-responsive">
        <table id="tbDocument" class="table">
            <thead>
                <tr>
                    <th>เอกสาร</th>
                    @*<th class="text-center" style="max-width: 150px;">สถานะการอัปโหลด</th>*@
                    <th class="text-center" style="max-width: 250px;">อัปโหลด</th>
                </tr>
            </thead>
            <tbody>
                @*@for (var index = 0; index < Model.Count; index++)
                    {
                        var line = Model[index];*@
                <tr ng-repeat="line in documentList">
                    <td class="text-left">
                        <span class="font-weight-600">{{line.DOC_TYPE_NAME}}</span>
                    </td>
                    @*<td class="text-center">
                            <span class="text-danger" ng-hide="line.UPLOAD_STATUS">ยังไม่ส่งเอกสาร</span>
                            <span class="text-warning" ng-show="line.UPLOAD_STATUS === 'N'">อัปโหลดเอกสารไม่สำเร็จ</span>
                            <span class="text-success" ng-show="line.UPLOAD_STATUS === 'Y'">อัปโหลดเอกสารสำเร็จ</span>
                            <span class="text-info" ng-show="line.UPLOAD_STATUS === 'W'">กำลังอัปโหลดเอกสาร...</span>
                        </td>*@
                    <td class="text-center" ng-show="line.UPLOAD_STATUS === 'Y'">
                        <a class="ml-1 btn btn-outline-success"
                           target="_blank"
                           href="#"
                           ng-href='@Url.Action("DownloadFromTemp","Upload")?testtypeid={{line.TEST_TYPE_ID}}&fileName={{line.FILE_NAME}}&fileType={{line.FILE_TYPE}}&docguid={{line.DOC_GUID}}'>
                            <i class="far fa-file-pdf"></i>&nbsp;
                            ดูเอกสาร
                        </a>
                    </td>
                    <td class="text-center" ng-show="line.UPLOAD_STATUS !== 'Y'">

                    </td>
                </tr>
                @* }*@
            </tbody>
        </table>
    </div>
}

<script src="~/Scripts/views/upload-docs.js?_=20220512"></script>